### ISSUE TITLE
WC3270/keymap do not recognize the difference between NORMAL RETURN KEY and NUMPAD RETURN KEY

### ISSUE THREAD

**Issue by marcus-mello** [pmattes/Wx3270-New#9]
Hi folks,      (see attached TXT description)

WC3270/keymap do not recognize the difference between NORMAL RETURN KEY and NUMPAD RETURN KEY

I'm used to work with NORMAL RETURN KEY as NewLine(), and NUMPAD RETURN KEY as Enter()
I prefer WC3270 because it is the most clean 3270 emulator that I found.
It's really good and fast.
The WX3270 has the same issue.

I followed this orientations:

https://x3270.miraheze.org/wiki/Wc3270/keymap
-----------------------------------------------------------------------------
The Extended modifier
Syntactically, the Extended modifier looks like a modifier key, but it is actually an extra attribute that Windows includes with certain keys. For example, the Enter key on the main keyboard is reported as the VKEY RETURN, but the Enter key on the numeric keypad is reported as the VKEY RETURN with the Extended modifier. To define separate actions for the two Enter keys, you could define a keymap like this:
<Key>RETURN: Newline()
Extended<Key>RETURN: Enter()      <--- EXTENDED ESPECIFIED IN THE WEB PAGE
-----------------------------------------------------------------------------

And this is my keyboard file:

FILE foo.wc3270km
-----------------------------------------------------------------------------
<Key>RETURN: Newline()
RightCtrl<Key>CTRL: Enter()
LeftCtrl<Key>CTRL: Reset()
<Key>END: EraseEOF()
<Key>PAGEUP: PF(7)
<Key>PAGEDOWN: PF(8)
Extended<Key>RETURN: Enter()     <--- AS ESPECIFIED IN THE WEB PAGE
-----------------------------------------------------------------------------

I got this message:

STARTING WC3270
-----------------------------------------------------------------------------
wc3270 v4.2ga6 Wed Sep 28 00:49:07 UTC 2022 pdm
Copyright 1989-2022 by Paul Mattes, GTRC and others.

Type 'show copyright' for full copyright information.
Type 'help' for help information.

Keymap foo, line 7: Unknown modifier     <------------ ERROR IN LINE 7
[Press <Enter>]
-----------------------------------------------------------------------------
p.s.
Removing the line 7 from keyboard file, all the other key definitions works fine.

BELOW, THE -TRACE LOG WITH THE DIFFERECE BETWEEN KEYS
The first RETURN is ok, changed to NewLine()
The second one SHOULD BE Enter() as especified in keyboard file.

https://x3270.miraheze.org/wiki/Wc3270/keymap

"How to figure out what keys are being generated"
"Start wc3270 with the -trace command-line option."

RESULTS IN x3trc.4072.txt
-----------------------------------------------------------------------------
NORMAL RETURN KEY
(...)                                                                  LOOK THIS
20221112.032135.849 Got event 0x2                                   VVVVVVVVVVVVVVVVVVVV
20221112.032135.849 KeyDown vkey 0xd (RETURN) scan 0x1c char U+000d state 0x20 (NumLock)
20221112.032135.849  [xk 0xd0000] <Key>RETURN ->lookup_key(0x000d0000, 0x20)
20221112.032135.849  foo:1 -> Newline()
20221112.032135.850 Macro[#13.2] 'Newline()'
20221112.032135.850 keymap -> Newline()

NUMPAD RETURN KEY
(...)                                                                  LOOK THIS
20221112.032138.905 Got event 0x2                                   VVVVVVVVVVVVVVVVVVVVVVVVVVVVV
20221112.032138.905 KeyDown vkey 0xd (RETURN) scan 0x1c char U+000d state 0x120 (NumLock Enhanced)
20221112.032138.905  [xk 0xd0000] <Key>RETURN ->lookup_key(0x000d0000, 0x120)
20221112.032138.905  foo:1 -> Newline()
20221112.032138.905 Macro[#14.2] 'Newline()'
20221112.032138.905 keymap -> Newline()
-----------------------------------------------------------------------------
[20221112_WC3270 keyboard issue.txt](https://github.com/pmattes/Wx3270-New/files/9994118/20221112_WC3270.keyboard.issue.txt)

**Comment by pmattes** [comment]
My apologies -- the Wiki was wrong. The proper modifier for the keypad Enter key is 'Enhanced', not 'Extended'. I have corrected the Wiki.

**Comment by marcus-mello** [comment]
Hi Paul!
Thank you by your attention, but still not working.  :(

Sorry, but the NUMPAD ENTER key still doing **mirroring** the keyboard ENTER key, even after modifying foo file with the **Enhanced** word.

Please see attached files: 
   foo.wc3270km
   x3trc.9312.txt (-trace file lightly commented)


NEW FOO FILE
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
RightCtrl\<Key\>CTRL: Enter()
LeftCtrl\<Key\>CTRL: Reset()
\<Key\>END: EraseEOF()
\<Key\>PAGEUP: PF(7)
\<Key\>PAGEDOWN: PF(8)
\<Key\>RETURN: Newline()
Enhanced\<Key\>RETURN: Enter()
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 


BELOW THE KEYS SEQUENCE THAT I TYPED:
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
1
1
1
keypad 1
keypad 1
keypad 1
ENTER
ENTER
ENTER
keypad ENTER
keypad ENTER
keypad ENTER
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 

[x3trc.9312.txt](https://github.com/pmattes/Wx3270-New/files/9997220/x3trc.9312.txt)

[foo.wc3270km.txt](https://github.com/pmattes/Wx3270-New/files/9997215/foo.wc3270km.txt)

**Comment by pmattes** [comment]
Hmm, looks like another error in the Wiki. If you want to map both **Enhanced&lt;Key>RETURN** and **&lt;Key>RETURN**, the **Enhanced** entry must appear first.

I have corrected the Wiki.

**Comment by pmattes** [comment]
Excellent!
